#!/usr/bin/python
#from metap2p.factory import ServerFactory
# vim: set filetype=python

#
# This is a bootstrap application for MetaP2P
#

import os, sys
metap2p_root = os.path.join(sys.prefix, "share", "metap2p")
metap2p_config = os.path.join(metap2p_root, "config")

from metap2p import initenv

#
# if configuration does not specify base_dir (which it should not in a bootstrap application)
# first argument here will be assumed as the base_dir.
# second is the configuration directory.
#
def main(argv):
  server = initenv(metap2p_root, metap2p_config)
  server.run()

if __name__ == '__main__':
  sys.exit(main(sys.argv[1:]))
